repos:
  - repo: https://github.com/psf/black
    rev: 21.5b0
    hooks:
      - id: black
        args: [--config=black.toml]
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        additional_dependencies:
          [
            mccabe,
            pycodestyle,
            pyflakes,
            pep8-naming,
            flake8-bugbear,
            flake8-comprehensions,
          ]
